frontend:
  url: https://primeshopprovip.vercel.app/

jwt:
  secret: "day-la-mot-cai-key-bi-mat-rat-dai-va-phuc-tap-khong-ai-doan-duoc-123456"
  expiration: 86400000

vnpay:
  tmn-code: KDL5BE9X
  secret-key: 85QP08M07Q2BBC92X3U9U91N3929J5YH
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: https://backend-primeshop.onrender.com/api/payment/vnpay/return

paypal:
  client-id: AeJcwxffoCD9s1VnJ3jxo54lpTtnEGA01CfjUSJQNWGxWGTfLUZczZiEU9f8A6vbFaHlHtDY24MWE9Wi
  client-secret: EIvU6tEMnRN77yJBch8dEfAzMeOGE1GC2gxm6rr_VQYB5ga08toyHrmwJTxKTDl_FM-6KcoDgDZIWoSV
  base-url: https://api-m.sandbox.paypal.com
  mode: sandbox

momo:
  partnerCode: MOMO
  accessKey: F8BBA842ECF85
  secretKey: K951B6PE1waDMi640xX08PD3vg6EkVlz
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  returnUrl: https://backend-primeshop.onrender.com/api/payment/momo/return
  notifyUrl: https://backend-primeshop.onrender.com/api/momo/notify