services:
  - type: web
    name: prime-shop-backend
    runtime: docker  # Change from 'java' to 'docker'
    plan: free
    # No need for buildCommand or startCommand since Dockerfile handles them
    # envVars:
    #   - key: JAVA_HOME
    #     value: /usr/lib/jvm/java-17-openjdk-amd64  # Not needed in Docker