# spring.datasource.url=jdbc:postgresql://dpg-d1bd79muk2gs739l882g-a.oregon-postgres.render.com:5432/primeshop
# spring.datasource.username=primeshop_user
# spring.datasource.password=J9kljCRvg1Ctqk00mNhntBlZ3AOmF75c

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PrimeShop;integratedSecurity=true;encrypt=false;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
server.address=0.0.0.0

server.port=8080
server.ssl.enable=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Tphat1706
server.ssl.key-alias=tomcat

# VNPay Configuration
vnpay.tmn-code=P8WZY8S4
vnpay.secret-key=AYAZFPB4UZMSBE23W110JC1WPVMG0DOV
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment-result
vnpay.ipn-url=http://localhost:8080/api/payment/vnpay/installment/callback

# VNPay Installment Configuration
vnpay.installment.interest-rates.3=8.5
vnpay.installment.interest-rates.6=9.0
vnpay.installment.interest-rates.9=9.5
vnpay.installment.interest-rates.12=10.0
vnpay.installment.interest-rates.18=10.5
vnpay.installment.interest-rates.24=11.0
vnpay.installment.max-installment-months=24
vnpay.installment.min-installment-months=3
vnpay.installment.min-amount=1000000
vnpay.installment.max-amount=50000000
vnpay.installment.payment-timeout-minutes=15

