# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PrimeShop;integratedSecurity=true;encrypt=false;trustServerCertificate=true;
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# spring.datasource.url=jdbc:postgresql://localhost:5432/PrimeShop
# spring.datasource.username=postgres
# spring.datasource.password=tphat176

spring.datasource.url=jdbc:postgresql://dpg-d4n4upre5dus738rmuj0-a.singapore-postgres.render.com:5432/primeshop_j44k
spring.datasource.username=primeshop_j44k_user
spring.datasource.password=yYWIv6NrETJ7Zayyx28PmgNqKDD26rKu

# Hibernate không động chạm vào schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway là nguồn quản lý schema chính
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false
spring.flyway.fail-on-missing-locations=false
spring.flyway.locations=classpath:db/migration

# Đảm bảo Hibernate chỉ load sau Flyway
spring.jpa.defer-datasource-initialization=false

# Nếu có file data.sql thì vẫn cho chạy sau Flyway
spring.sql.init.mode=always
spring.jpa.open-in-view=true

server.port=${PORT:10000}
server.address=0.0.0.0
server.forward-headers-strategy=native
server.ssl.enable=false
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Tphat1706
server.ssl.key-alias=tomcat

# VNPay Configuration
vnpay.tmn-code=P8WZY8S4
vnpay.secret-key=AYAZFPB4UZMSBE23W110JC1WPVMG0DOV
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment-result
vnpay.ipn-url=http://localhost:8080/api/payment/vnpay/installment/callback

# VNPay Installment Configuration
vnpay.installment.interest-rates.3=8.5
vnpay.installment.interest-rates.6=9.0
vnpay.installment.interest-rates.9=9.5
vnpay.installment.interest-rates.12=10.0
vnpay.installment.interest-rates.18=10.5
vnpay.installment.interest-rates.24=11.0
vnpay.installment.max-installment-months=24
vnpay.installment.min-installment-months=3
vnpay.installment.min-amount=1000000
vnpay.installment.max-amount=50000000
vnpay.installment.payment-timeout-minutes=15



